const flowErrorCodes = Object.freeze({
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  FLOW_NOT_FOUND: 'FLOW_NOT_FOUND',
  FLOW_VALIDATION_FAILED: 'FLOW_VALIDATION_FAILED',
  FLOW_VERSION_NOT_FOUND: 'FLOW_VERSION_NOT_FOUND',
  FLOW_SUBMISSION_VALIDATION_FAILED: 'FLOW_SUBMISSION_VALIDATION_FAILED',
  FLOW_SUBMISSION_FAILED: 'FLOW_SUBMISSION_FAILED',
  FLOW_CREATION_FAILED: 'FLOW_CREATION_FAILED',
  FLOW_META_SYNC_FAILED: 'FLOW_META_SYNC_FAILED',
  FLOW_PUBLISH_FAILED: 'FLOW_PUBLISH_FAILED',
  FLOW_DEPRECATE_FAILED: 'FLOW_DEPRECATE_FAILED',
  FLOW_DELETE_FAILED: 'FLOW_DELETE_FAILED',
  FLOW_RETIRE_FAILED: 'FLOW_RETIRE_FAILED',
  FLOW_STATUS_SYNC_FAILED: 'FLOW_STATUS_SYNC_FAILED',
  FLOW_CLONE_FAILED: 'FLOW_CLONE_FAILED',
  FLOW_CONFLICT: 'FLOW_CONFLICT',
  WEBHOOK_UNAUTHORIZED: 'WEBHOOK_UNAUTHORIZED',
});

export default flowErrorCodes;
