
-- Create database if not exists
CREATE DATABASE IF NOT EXISTS team_service;
USE team_service;

-- Department Table
CREATE TABLE IF NOT EXISTS department (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Agent Table
CREATE TABLE IF NOT EXISTS agent (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	department VARCHAR(100) NOT NULL,
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
